name: Webpack Build

on:
  push:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Webpack
      run: npx webpack

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist/
